/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test fun someOtherMethodReturnsFalse() {
        val classUnderTest = Library()
        assertTrue(!classUnderTest.someOtherMethod(), "someOtherMethod should return 'false'")
    }

    @Test fun thirdMethodReturnsInt() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.thirdMethod() is Int, "thirdMethod should return an Int")
    }
}
