name: Run Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: cd ${{github.workspace}}
      - run: ./gradlew test


