name: Run Tests

on:
  push:
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - "Dockerfile"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: ./gradlew test


